BATCH_SIZE = 16
IMG_SIZE = [224, 224]
CHANNELS = 3
VOCAB_SIZE = 50000
NUM_LABELS = 7
TRAIN_SIZE = 1000
VAL_SIZE = 500

ORIGINAL_DATASET_PATH = './datasets/claims_for_ica/train'
STORED_MODEL_FILE = 'saved_models/trainedModel.h5'
CLASSIFIED_DOCUMENTS_DIRECTORY = "classified_documents/"
